[tool.poetry]
name = "room-booking-system"
version = "0.1.0"
description = ""
authors = ["tliangso <earth78203@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
django = "^4.2.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
